package za.ac.richfield.dijong.data;

import static org.junit.Assert.assertEquals;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;

import androidx.room.Room;
import androidx.test.core.app.ApplicationProvider;
import androidx.test.ext.junit.runners.AndroidJUnit4;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.util.List;

import za.ac.richfield.dijong.data.entity.PantryItem;

/**
 * Builds a database exactly as version 1 of the app left it, then opens it with the current
 * Room setup to check that {@link DijongDatabase#MIGRATION_1_2} keeps every pantry item and
 * files it under "Other".
 */
@RunWith(AndroidJUnit4.class)
public class MigrationTest {

    private static final String TEST_DB = "migration-test.db";

    private Context context;

    @Before
    public void createVersionOneDatabase() {
        context = ApplicationProvider.getApplicationContext();
        context.deleteDatabase(TEST_DB);
        SQLiteDatabase db = context.openOrCreateDatabase(TEST_DB, Context.MODE_PRIVATE, null);
        // Version 1 schema, as generated by Room before the category column existed
        db.execSQL("CREATE TABLE `pantry_items` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "
                + "`name` TEXT NOT NULL, `quantity` REAL NOT NULL, `unit` TEXT, `expiry_date` INTEGER)");
        db.execSQL("CREATE TABLE `recipes` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "
                + "`name` TEXT NOT NULL, `prep_steps` TEXT)");
        db.execSQL("CREATE TABLE `recipe_ingredients` (`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "
                + "`recipeId` INTEGER NOT NULL, `ingredient_name` TEXT NOT NULL, `required_quantity` REAL NOT NULL, "
                + "`unit` TEXT, FOREIGN KEY(`recipeId`) REFERENCES `recipes`(`id`) ON UPDATE NO ACTION ON DELETE CASCADE )");
        db.execSQL("CREATE INDEX `index_recipe_ingredients_recipeId` ON `recipe_ingredients` (`recipeId`)");
        db.execSQL("INSERT INTO pantry_items (name, quantity, unit, expiry_date) VALUES ('Butternut', 800, 'g', 20725)");
        db.execSQL("INSERT INTO pantry_items (name, quantity, unit, expiry_date) VALUES ('Onions', 2, 'unit', NULL)");
        db.setVersion(1);
        db.close();
    }

    @After
    public void deleteDatabase() {
        context.deleteDatabase(TEST_DB);
    }

    @Test
    public void migrate1To2_keepsPantryItemsAndDefaultsCategoryToOther() {
        DijongDatabase migrated = Room.databaseBuilder(context, DijongDatabase.class, TEST_DB)
                .addMigrations(DijongDatabase.MIGRATION_1_2)
                .allowMainThreadQueries()
                .build();
        try {
            List<PantryItem> items = migrated.pantryDao().getAllItemsSync();

            assertEquals(2, items.size());
            PantryItem butternut = items.get(0).getName().equals("Butternut") ? items.get(0) : items.get(1);
            assertEquals(800.0, butternut.getQuantity(), 0.0001);
            assertEquals("g", butternut.getUnit());
            assertEquals(Long.valueOf(20725L), butternut.getExpiryDate());
            for (PantryItem item : items) {
                assertEquals(IngredientCategory.OTHER, item.getCategoryEnum());
            }
        } finally {
            migrated.close();
        }
    }
}
